""" API Blueprint """

from flask import Blueprint

from ..decorators import etag


api = Blueprint('api', __name__)


@api.after_request
@etag
def after_request(response):
    """ Apply ETag to all HTTP responses generated by this blueprint """

    return response


from . import errors, persons
