"""Event model

Revision ID: 1051a18dc81
Revises: 484f831fea3
Create Date: 2015-06-08 10:50:16.669020

"""

# revision identifiers, used by Alembic.
revision = '1051a18dc81'
down_revision = '484f831fea3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flapi_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ENABLED', 'DISABLED'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['legacy_id'], ['flapi_legacy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flapi_event_day'), 'flapi_event', ['day'], unique=False)
    op.create_index(op.f('ix_flapi_event_month'), 'flapi_event', ['month'], unique=False)
    op.create_index(op.f('ix_flapi_event_status'), 'flapi_event', ['status'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flapi_event_status'), table_name='flapi_event')
    op.drop_index(op.f('ix_flapi_event_month'), table_name='flapi_event')
    op.drop_index(op.f('ix_flapi_event_day'), table_name='flapi_event')
    op.drop_table('flapi_event')
    ### end Alembic commands ###
