"""Attachment model

Revision ID: 2619b9cdfa2
Revises: 1051a18dc81
Create Date: 2015-06-09 01:54:10.791212

"""

# revision identifiers, used by Alembic.
revision = '2619b9cdfa2'
down_revision = '1051a18dc81'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flapi_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_url', sa.String(length=150), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flapi_event_messages',
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('attachment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attachment_id'], ['flapi_attachment.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['flapi_event.id'], )
    )
    op.create_table('flapi_event_photos',
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('attachment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attachment_id'], ['flapi_attachment.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['flapi_event.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flapi_event_photos')
    op.drop_table('flapi_event_messages')
    op.drop_table('flapi_attachment')
    ### end Alembic commands ###
