"""Event.last_run to track event last run date

Revision ID: 2892f0c6c0f
Revises: 547c09eaa73
Create Date: 2015-11-03 13:38:18.521038

"""

# revision identifiers, used by Alembic.
revision = '2892f0c6c0f'
down_revision = '547c09eaa73'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flapi_event', sa.Column('last_run', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flapi_event', 'last_run')
    ### end Alembic commands ###
