"""Event.legacy_id not nullable

Revision ID: 2893ba3ff03
Revises: 2619b9cdfa2
Create Date: 2015-06-15 15:41:40.970573

"""

# revision identifiers, used by Alembic.
revision = '2893ba3ff03'
down_revision = '2619b9cdfa2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flapi_event', 'legacy_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flapi_event', 'legacy_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    ### end Alembic commands ###
