"""empty message

Revision ID: 3701d7fe691
Revises: 202ca47c65c
Create Date: 2015-05-20 16:05:46.800427

"""

# revision identifiers, used by Alembic.
revision = '3701d7fe691'
down_revision = '202ca47c65c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flapi_persons', sa.Column('username', sa.String(length=32), nullable=False))
    op.create_index(op.f('ix_flapi_persons_username'), 'flapi_persons', ['username'], unique=True)
    op.drop_index('ix_flapi_persons_email', table_name='flapi_persons')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_flapi_persons_email', 'flapi_persons', ['email'], unique=True)
    op.drop_index(op.f('ix_flapi_persons_username'), table_name='flapi_persons')
    op.drop_column('flapi_persons', 'username')
    ### end Alembic commands ###
