"""Legacy.owner_id not nullable

Revision ID: 484f831fea3
Revises: 3701d7fe691
Create Date: 2015-05-23 19:32:55.134139

"""

# revision identifiers, used by Alembic.
revision = '484f831fea3'
down_revision = '3701d7fe691'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flapi_legacy', 'owner_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flapi_legacy', 'owner_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    ### end Alembic commands ###
