"""Event.run_count to track event execution

Revision ID: 547c09eaa73
Revises: 9bfa9b0fe0
Create Date: 2015-10-28 09:16:53.020733

"""

# revision identifiers, used by Alembic.
revision = '547c09eaa73'
down_revision = '9bfa9b0fe0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flapi_event', sa.Column('run_count', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flapi_event', 'run_count')
    ### end Alembic commands ###
