"""EmailTemplate model

Revision ID: 9bfa9b0fe0
Revises: 2893ba3ff03
Create Date: 2015-08-11 17:08:07.622375

"""

# revision identifiers, used by Alembic.
revision = '9bfa9b0fe0'
down_revision = '2893ba3ff03'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flapi_email_templates',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flapi_email_templates')
    ### end Alembic commands ###
